[package]
name = "grib-cli"
description = """
CLI application for processing GRIB format data, built on the top of the library `grib`
"""
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
rust-version = "1.80"

[[bin]]
name = "gribber"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = "0.4.23"
clap = "4.1"
clap_complete = "4"
console = "0.15"
regex = "1.6"

[target.'cfg(unix)'.dependencies]
grib = { path = "..", version = "=0.10.2", features = ["gridpoints-proj"] }
pager = "0.16"
which = "4"

[target.'cfg(not(unix))'.dependencies]
grib = { path = "..", version = "=0.10.2" }

[dev-dependencies]
assert_cmd = "2"
flate2 = "1.0"
predicates = "3"
tempfile = "3"
xz2 = "0.1"
